// SPDX-License-Identifier: Apache-2.0

// Package derive runs §4.4 derivation proofs: a rule declared in policy
// states that outputs O are deterministically produced from inputs I by
// pinned command C, and the verifier re-runs C against the tree and
// byte-diffs the regenerated outputs against the committed ones. The proof
// is reproducibility, not identity — who ran the generator is irrelevant.
//
// Byte-identical regeneration means the output paths inherit the minimum
// trust level of the input paths as of the same tree; any difference voids
// the proof for this release — the outputs are classified by their commits'
// own provenance, and the discrepancy is reported (never silently absorbed).
// Formatting-only rules are the degenerate case: inputs = outputs,
// command = formatter, and an already-formatted tree reproduces itself.
//
// Derivation proofs are the scheme's only exception to weakest-link flooring
// (ADR-004), principled because they are verified, not declared. Running the
// pinned command mutates the tree it runs in, so callers hand Run a
// disposable checkout, never the working tree being verified. No clock, no
// network access of its own — the command comes from the policy file, which
// is itself meta-path-protected (§5.4): the config protects the system.
package derive

import (
	"crypto/sha256"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"

	"github.com/semver-trust/semver-trust-go/internal/policy"
	"github.com/semver-trust/semver-trust-go/internal/trust"
)

// Verdict is the outcome of running one derivation rule.
type Verdict struct {
	// Rule is the rule's policy name.
	Rule string
	// Verified reports byte-identical regeneration of every output path.
	Verified bool
	// Diffs lists the output paths whose regenerated bytes differ from the
	// committed ones — the reported discrepancy that voids the proof.
	// Deleted and newly-appearing outputs count as diffs.
	Diffs []string
}

// Run executes a derivation rule's pinned command in dir (a disposable
// checkout of the tree under verification) and byte-diffs the output paths
// against their committed state. A rule whose command fails, or whose output
// globs match nothing, is an error — an unrunnable proof proves nothing and
// must not read as "no exception applies".
func Run(dir string, rule policy.Derivation) (Verdict, error) {
	before, err := snapshot(dir, rule.Outputs)
	if err != nil {
		return Verdict{}, err
	}
	if len(before) == 0 {
		return Verdict{}, fmt.Errorf("derive: rule %q: no committed files match its outputs", rule.Name)
	}

	cmd := exec.Command("sh", "-c", rule.Command)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		return Verdict{}, fmt.Errorf("derive: rule %q: command failed: %w\n%s", rule.Name, err, out)
	}

	after, err := snapshot(dir, rule.Outputs)
	if err != nil {
		return Verdict{}, err
	}

	diffSet := map[string]bool{}
	for path, digest := range before {
		if after[path] != digest {
			diffSet[path] = true
		}
	}
	for path := range after {
		if _, existed := before[path]; !existed {
			diffSet[path] = true
		}
	}
	diffs := make([]string, 0, len(diffSet))
	for path := range diffSet {
		diffs = append(diffs, path)
	}
	sort.Strings(diffs)

	return Verdict{Rule: rule.Name, Verified: len(diffs) == 0, Diffs: diffs}, nil
}

// InputsFloor computes the minimum trust level of a rule's input paths as of
// the tree (§4.4): the floor over the range commits touching any input path.
// This is the level verified outputs inherit. No commit touching the inputs
// is an error — an inheritance source must exist to inherit from.
func InputsFloor(commits []trust.Commit, rule policy.Derivation) (trust.Level, error) {
	floor := trust.T3
	found := false
	for _, commit := range commits {
		touches, err := touchesAny(commit.Paths, rule.Inputs)
		if err != nil {
			return 0, err
		}
		if !touches {
			continue
		}
		found = true
		if commit.Level < floor {
			floor = commit.Level
		}
	}
	if !found {
		return 0, fmt.Errorf("derive: rule %q: no commit in range touches its inputs", rule.Name)
	}
	return floor, nil
}

// Facts assembles the aggregation-facing view of a rule's outcome: the
// trust.DerivationFacts that ScopeFloors consumes (§5.2). A void proof
// carries Verified=false, so the outputs contribute their commits' own
// levels.
func Facts(rule policy.Derivation, verdict Verdict, inputsFloor trust.Level) *trust.DerivationFacts {
	return &trust.DerivationFacts{
		Outputs:        rule.Outputs,
		Verified:       verdict.Verified,
		InheritedLevel: inputsFloor,
	}
}

func touchesAny(paths, globs []string) (bool, error) {
	for _, path := range paths {
		for _, glob := range globs {
			ok, err := trust.MatchGlob(glob, path)
			if err != nil || ok {
				return ok, err
			}
		}
	}
	return false, nil
}

// snapshot digests every file under dir matching the output globs, keyed by
// slash-relative path. VCS metadata is skipped; everything else in a
// disposable checkout is fair game for a generator to write.
func snapshot(dir string, globs []string) (map[string][32]byte, error) {
	digests := map[string][32]byte{}
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == ".git" {
				return filepath.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		for _, glob := range globs {
			ok, err := trust.MatchGlob(glob, rel)
			if err != nil {
				return err
			}
			if ok {
				data, err := os.ReadFile(path)
				if err != nil {
					return err
				}
				digests[rel] = sha256.Sum256(data)
				break
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return digests, nil
}
